// std library
use std::num::NonZeroU32;
use std::sync::Arc;
use std::time::Duration;

// external crates
use async_trait::async_trait;
use backon::{ExponentialBuilder, Retryable};
use governor::clock::DefaultClock;
use governor::state::{InMemoryState, NotKeyed};
use governor::{Quota, RateLimiter as GovRateLimiter};
use reqwest::Client;
use serde::Deserialize;
use tracing::{debug, warn};

// internal crate
use super::PipelineError;
use crate::config::Config;

// ---------------------------------------------------------------------------
// Type aliases
// ---------------------------------------------------------------------------

type RateLimiter = GovRateLimiter<NotKeyed, InMemoryState, DefaultClock>;

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// Maximum slot range per `getBlocks` RPC call.
const MAX_GET_BLOCKS_RANGE: u64 = 500_000;

/// Maximum pubkeys per `getMultipleAccounts` RPC call.
const MAX_MULTIPLE_ACCOUNTS_BATCH: usize = 100;

/// JSON-RPC error code for skipped slots.
const SKIPPED_SLOT_ERROR_CODE: i64 = -32009;

// ---------------------------------------------------------------------------
// Public RPC response types
// ---------------------------------------------------------------------------

/// Raw block from Solana RPC (before decoding instruction data).
#[derive(Debug, Clone)]
pub struct RpcBlock {
    pub slot: u64,
    pub block_time: Option<i64>,
    pub transactions: Vec<RpcTransaction>,
}

/// Raw transaction from Solana RPC.
#[derive(Debug, Clone)]
pub struct RpcTransaction {
    pub signature: String,
    pub slot: u64,
    pub success: bool,
    pub account_keys: Vec<String>,
    pub instructions: Vec<RpcInstruction>,
    pub inner_instructions: Vec<RpcInnerInstructionGroup>,
}

/// A single instruction within a transaction.
#[derive(Debug, Clone)]
pub struct RpcInstruction {
    pub program_id_index: u8,
    pub data: Vec<u8>,
    pub accounts: Vec<u8>,
}

/// Group of inner instructions generated by CPI.
#[derive(Debug, Clone)]
pub struct RpcInnerInstructionGroup {
    pub index: u8,
    pub instructions: Vec<RpcInstruction>,
}

/// Account info returned by getMultipleAccounts.
#[derive(Debug, Clone)]
pub struct RpcAccountInfo {
    pub pubkey: String,
    pub data: Vec<u8>,
    pub lamports: u64,
    pub owner: String,
}

// ---------------------------------------------------------------------------
// JSON-RPC envelope types (private, for deserialization)
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
struct JsonRpcResponse<T> {
    result: Option<T>,
    error: Option<JsonRpcError>,
}

#[derive(Debug, Clone, Deserialize)]
struct JsonRpcError {
    code: i64,
    message: String,
}

// ---------------------------------------------------------------------------
// Raw deserialization types for getBlock
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
struct RawGetBlockResult {
    #[serde(rename = "blockTime")]
    block_time: Option<i64>,
    transactions: Option<Vec<RawBlockTransaction>>,
}

#[derive(Deserialize)]
struct RawBlockTransaction {
    transaction: RawTransactionPayload,
    meta: Option<RawTransactionMeta>,
}

#[derive(Deserialize)]
struct RawTransactionPayload {
    message: RawMessage,
    signatures: Vec<String>,
}

#[derive(Deserialize)]
struct RawMessage {
    #[serde(rename = "accountKeys")]
    account_keys: Vec<String>,
    instructions: Vec<RawInstruction>,
}

#[derive(Deserialize)]
struct RawInstruction {
    #[serde(rename = "programIdIndex")]
    program_id_index: u8,
    data: String, // base58-encoded
    accounts: Vec<u8>,
}

#[derive(Deserialize)]
struct RawTransactionMeta {
    err: Option<serde_json::Value>,
    #[serde(rename = "innerInstructions")]
    inner_instructions: Option<Vec<RawInnerInstructionGroup>>,
    #[serde(rename = "loadedAddresses", default)]
    loaded_addresses: Option<RawLoadedAddresses>,
}

/// Addresses resolved from v0 transaction address lookup tables.
#[derive(Deserialize)]
struct RawLoadedAddresses {
    #[serde(default)]
    writable: Vec<String>,
    #[serde(default)]
    readonly: Vec<String>,
}

#[derive(Deserialize)]
struct RawInnerInstructionGroup {
    index: u8,
    instructions: Vec<RawInstruction>,
}

// ---------------------------------------------------------------------------
// Raw deserialization types for getTransaction
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
#[allow(dead_code)] // block_time deserialized but not read (available for future use)
struct RawGetTransactionResult {
    slot: u64,
    transaction: RawTransactionPayload,
    meta: Option<RawTransactionMeta>,
    #[serde(rename = "blockTime")]
    block_time: Option<i64>,
}

// ---------------------------------------------------------------------------
// Raw deserialization types for getProgramAccounts
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
struct RawProgramAccount {
    pubkey: String,
}

// ---------------------------------------------------------------------------
// Raw deserialization types for getMultipleAccounts
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
struct RawGetMultipleAccountsResult {
    value: Vec<Option<RawAccountInfo>>,
}

#[derive(Deserialize)]
struct RawAccountInfo {
    data: Vec<String>, // [base64_data, "base64"]
    lamports: u64,
    owner: String,
}

// ---------------------------------------------------------------------------
// Traits
// ---------------------------------------------------------------------------

/// Trait for fetching blocks from Solana RPC.
#[async_trait]
pub trait BlockSource: Send + Sync {
    /// Get confirmed block slot numbers within a range.
    async fn get_blocks(&self, start_slot: u64, end_slot: u64) -> Result<Vec<u64>, PipelineError>;

    /// Fetch a block by slot. Returns `None` for skipped/empty slots.
    async fn get_block(&self, slot: u64) -> Result<Option<RpcBlock>, PipelineError>;

    /// Get the current highest processed slot.
    async fn get_slot(&self) -> Result<u64, PipelineError>;
}

/// Trait for fetching account data from Solana RPC.
#[async_trait]
pub trait AccountSource: Send + Sync {
    /// Fetch all account pubkeys for a program (using dataSlice trick).
    async fn get_program_accounts(&self, program_id: &str) -> Result<Vec<String>, PipelineError>;

    /// Fetch multiple accounts by pubkey (auto-batches in chunks of 100).
    async fn get_multiple_accounts(
        &self,
        pubkeys: &[String],
    ) -> Result<Vec<RpcAccountInfo>, PipelineError>;
}

// ---------------------------------------------------------------------------
// RpcClient
// ---------------------------------------------------------------------------

pub struct RpcClient {
    http: Client,
    rpc_url: String,
    rate_limiter: Arc<RateLimiter>,
    index_failed_txs: bool,
    retry_min_delay: Duration,
    retry_max_delay: Duration,
    retry_timeout: Duration,
}

impl RpcClient {
    pub fn new(config: &Config) -> Result<Self, PipelineError> {
        let rps = NonZeroU32::new(config.rpc_rps)
            .ok_or_else(|| PipelineError::Fatal("rpc_rps must be > 0".into()))?;

        let rate_limiter = Arc::new(GovRateLimiter::direct(Quota::per_second(rps)));

        let http = Client::builder()
            .timeout(Duration::from_secs(60))
            .build()
            .map_err(|e| PipelineError::Fatal(format!("HTTP client init failed: {e}")))?;

        Ok(Self {
            http,
            rpc_url: config.rpc_url.clone(),
            rate_limiter,
            index_failed_txs: config.index_failed_txs,
            retry_min_delay: Duration::from_millis(config.retry_initial_ms),
            retry_max_delay: Duration::from_millis(config.retry_max_ms),
            retry_timeout: Duration::from_secs(config.retry_timeout_secs),
        })
    }

    /// Send a JSON-RPC 2.0 request (single attempt, no retry).
    async fn send_rpc_request(
        &self,
        method: &str,
        params: serde_json::Value,
    ) -> Result<serde_json::Value, PipelineError> {
        let body = serde_json::json!({
            "jsonrpc": "2.0",
            "id": 1,
            "method": method,
            "params": params,
        });

        let resp = self
            .http
            .post(&self.rpc_url)
            .json(&body)
            .send()
            .await
            .map_err(|e| {
                if e.is_timeout() {
                    PipelineError::RpcFailed(format!("timeout: {e}"))
                } else if e.is_connect() {
                    PipelineError::RpcFailed(format!("connection failed: {e}"))
                } else {
                    PipelineError::RpcFailed(format!("request failed: {e}"))
                }
            })?;

        let status = resp.status();
        if status == reqwest::StatusCode::TOO_MANY_REQUESTS {
            return Err(PipelineError::RateLimited);
        }
        if !status.is_success() {
            // 4xx client errors (except 429 handled above) are non-retryable
            if status.is_client_error() {
                return Err(PipelineError::Fatal(format!("HTTP {status}")));
            }
            // 5xx and other errors are retryable
            return Err(PipelineError::RpcFailed(format!("HTTP {status}")));
        }

        let rpc_resp: JsonRpcResponse<serde_json::Value> = resp
            .json()
            .await
            .map_err(|e| PipelineError::RpcFailed(format!("response parse failed: {e}")))?;

        if let Some(err) = rpc_resp.error {
            return Err(classify_rpc_error(err));
        }

        rpc_resp
            .result
            .ok_or_else(|| PipelineError::RpcFailed("null result without error".into()))
    }

    /// Send a JSON-RPC 2.0 request (single attempt, no retry). Returns `None` for null result.
    async fn send_rpc_request_optional(
        &self,
        method: &str,
        params: serde_json::Value,
    ) -> Result<Option<serde_json::Value>, PipelineError> {
        let body = serde_json::json!({
            "jsonrpc": "2.0",
            "id": 1,
            "method": method,
            "params": params,
        });

        let resp = self
            .http
            .post(&self.rpc_url)
            .json(&body)
            .send()
            .await
            .map_err(|e| {
                if e.is_timeout() {
                    PipelineError::RpcFailed(format!("timeout: {e}"))
                } else if e.is_connect() {
                    PipelineError::RpcFailed(format!("connection failed: {e}"))
                } else {
                    PipelineError::RpcFailed(format!("request failed: {e}"))
                }
            })?;

        let status = resp.status();
        if status == reqwest::StatusCode::TOO_MANY_REQUESTS {
            return Err(PipelineError::RateLimited);
        }
        if !status.is_success() {
            if status.is_client_error() {
                return Err(PipelineError::Fatal(format!("HTTP {status}")));
            }
            return Err(PipelineError::RpcFailed(format!("HTTP {status}")));
        }

        let rpc_resp: JsonRpcResponse<serde_json::Value> = resp
            .json()
            .await
            .map_err(|e| PipelineError::RpcFailed(format!("response parse failed: {e}")))?;

        if let Some(err) = rpc_resp.error {
            return Err(classify_rpc_error(err));
        }

        Ok(rpc_resp.result)
    }

    /// Send a JSON-RPC request with rate limiting and retry. Returns `None` for null result.
    async fn rpc_request_optional(
        &self,
        method: &str,
        params: serde_json::Value,
    ) -> Result<Option<serde_json::Value>, PipelineError> {
        let method_owned = method.to_string();
        let method_for_log = method_owned.clone();
        let params_clone = params.clone();

        (|| async {
            self.rate_limiter.until_ready().await;
            self.send_rpc_request_optional(&method_owned, params_clone.clone())
                .await
        })
        .retry(
            ExponentialBuilder::default()
                .with_min_delay(self.retry_min_delay)
                .with_max_delay(self.retry_max_delay)
                .with_total_delay(Some(self.retry_timeout))
                .with_factor(2.0)
                .with_jitter()
                .without_max_times(),
        )
        .when(|e: &PipelineError| e.is_retryable())
        .notify(|err: &PipelineError, dur: Duration| {
            warn!(error = %err, delay = ?dur, method = %method_for_log, "retrying RPC call");
        })
        .await
    }

    /// Send a JSON-RPC request with rate limiting and retry.
    async fn rpc_request(
        &self,
        method: &str,
        params: serde_json::Value,
    ) -> Result<serde_json::Value, PipelineError> {
        let method_owned = method.to_string();
        let method_for_log = method_owned.clone();
        let params_clone = params.clone();

        (|| async {
            self.rate_limiter.until_ready().await;
            self.send_rpc_request(&method_owned, params_clone.clone())
                .await
        })
        .retry(
            ExponentialBuilder::default()
                .with_min_delay(self.retry_min_delay)
                .with_max_delay(self.retry_max_delay)
                .with_total_delay(Some(self.retry_timeout))
                .with_factor(2.0)
                .with_jitter()
                .without_max_times(),
        )
        .when(|e: &PipelineError| e.is_retryable())
        .notify(|err: &PipelineError, dur: Duration| {
            warn!(error = %err, delay = ?dur, method = %method_for_log, "retrying RPC call");
        })
        .await
    }
    /// Fetch a single transaction by signature.
    /// Returns `None` if the transaction is not found or not yet confirmed.
    pub async fn get_transaction(
        &self,
        signature: &str,
    ) -> Result<Option<RpcTransaction>, PipelineError> {
        let params = serde_json::json!([
            signature,
            {
                "encoding": "json",
                "maxSupportedTransactionVersion": 0,
                "commitment": "finalized"
            }
        ]);

        let maybe_value = self.rpc_request_optional("getTransaction", params).await?;

        let value = match maybe_value {
            Some(v) => v,
            None => return Ok(None),
        };

        let raw: RawGetTransactionResult = serde_json::from_value(value)
            .map_err(|e| PipelineError::RpcFailed(format!("getTransaction parse failed: {e}")))?;

        let success = raw.meta.as_ref().map(|m| m.err.is_none()).unwrap_or(true);

        let sig = match raw.transaction.signatures.first().cloned() {
            Some(s) => s,
            None => {
                warn!("getTransaction returned tx with empty signatures array");
                return Err(PipelineError::RpcFailed(
                    "getTransaction: transaction has no signatures".into(),
                ));
            }
        };

        let instructions = raw
            .transaction
            .message
            .instructions
            .iter()
            .map(parse_raw_instruction)
            .collect::<Result<Vec<_>, _>>()?;

        let inner_instructions = raw
            .meta
            .as_ref()
            .and_then(|m| m.inner_instructions.as_ref())
            .map(|groups| {
                groups
                    .iter()
                    .map(parse_raw_inner_instruction_group)
                    .collect::<Result<Vec<_>, _>>()
            })
            .transpose()?
            .unwrap_or_default();

        let mut account_keys = raw.transaction.message.account_keys;
        if let Some(meta) = &raw.meta {
            if let Some(loaded) = &meta.loaded_addresses {
                account_keys.extend(loaded.writable.iter().cloned());
                account_keys.extend(loaded.readonly.iter().cloned());
            }
        }

        Ok(Some(RpcTransaction {
            signature: sig,
            slot: raw.slot,
            success,
            account_keys,
            instructions,
            inner_instructions,
        }))
    }
}

// ---------------------------------------------------------------------------
// BlockSource implementation
// ---------------------------------------------------------------------------

#[async_trait]
impl BlockSource for RpcClient {
    async fn get_blocks(&self, start_slot: u64, end_slot: u64) -> Result<Vec<u64>, PipelineError> {
        let chunks = compute_block_chunks(start_slot, end_slot);
        let mut all_slots = Vec::new();

        for (chunk_start, chunk_end) in chunks {
            let params = serde_json::json!([
                chunk_start,
                chunk_end,
                { "commitment": "finalized" }
            ]);

            let value = self.rpc_request("getBlocks", params).await?;
            let slots: Vec<u64> = serde_json::from_value(value).map_err(|e| {
                PipelineError::RpcFailed(format!("getBlocks response parse failed: {e}"))
            })?;
            all_slots.extend(slots);
        }

        Ok(all_slots)
    }

    async fn get_block(&self, slot: u64) -> Result<Option<RpcBlock>, PipelineError> {
        let params = serde_json::json!([
            slot,
            {
                "encoding": "json",
                "transactionDetails": "full",
                "maxSupportedTransactionVersion": 0,
                "commitment": "finalized"
            }
        ]);

        match self.rpc_request("getBlock", params).await {
            Ok(value) => {
                let block = parse_block(slot, value, self.index_failed_txs)?;
                Ok(Some(block))
            }
            Err(PipelineError::SlotSkipped(_)) => {
                debug!(slot, "slot skipped");
                Ok(None)
            }
            Err(e) => Err(e),
        }
    }

    async fn get_slot(&self) -> Result<u64, PipelineError> {
        let params = serde_json::json!([{ "commitment": "finalized" }]);
        let value = self.rpc_request("getSlot", params).await?;
        serde_json::from_value(value)
            .map_err(|e| PipelineError::RpcFailed(format!("getSlot response parse failed: {e}")))
    }
}

// ---------------------------------------------------------------------------
// AccountSource implementation
// ---------------------------------------------------------------------------

#[async_trait]
impl AccountSource for RpcClient {
    async fn get_program_accounts(&self, program_id: &str) -> Result<Vec<String>, PipelineError> {
        let params = serde_json::json!([
            program_id,
            {
                "encoding": "base64",
                "dataSlice": { "offset": 0, "length": 0 },
                "commitment": "finalized"
            }
        ]);

        let value = self.rpc_request("getProgramAccounts", params).await?;
        let accounts: Vec<RawProgramAccount> = serde_json::from_value(value).map_err(|e| {
            PipelineError::RpcFailed(format!("getProgramAccounts response parse failed: {e}"))
        })?;

        Ok(accounts.into_iter().map(|a| a.pubkey).collect())
    }

    async fn get_multiple_accounts(
        &self,
        pubkeys: &[String],
    ) -> Result<Vec<RpcAccountInfo>, PipelineError> {
        let mut all_accounts = Vec::new();
        let batches = batch_pubkeys(pubkeys);

        for (batch_keys, batch_start) in batches {
            let params = serde_json::json!([
                batch_keys,
                { "encoding": "base64", "commitment": "finalized" }
            ]);

            let value = self.rpc_request("getMultipleAccounts", params).await?;
            let result: RawGetMultipleAccountsResult =
                serde_json::from_value(value).map_err(|e| {
                    PipelineError::RpcFailed(format!(
                        "getMultipleAccounts response parse failed: {e}"
                    ))
                })?;

            if result.value.len() > batch_keys.len() {
                return Err(PipelineError::RpcFailed(format!(
                    "getMultipleAccounts returned {} entries for {} keys",
                    result.value.len(),
                    batch_keys.len(),
                )));
            }

            for (i, maybe_account) in result.value.into_iter().enumerate() {
                if let Some(raw) = maybe_account {
                    let data = decode_base64_account_data(&raw.data)?;
                    all_accounts.push(RpcAccountInfo {
                        pubkey: pubkeys[batch_start + i].clone(),
                        data,
                        lamports: raw.lamports,
                        owner: raw.owner,
                    });
                }
            }
        }

        Ok(all_accounts)
    }
}

// ---------------------------------------------------------------------------
// Parsing helpers
// ---------------------------------------------------------------------------

/// Parse a raw getBlock JSON response into an `RpcBlock`.
fn parse_block(
    slot: u64,
    value: serde_json::Value,
    index_failed_txs: bool,
) -> Result<RpcBlock, PipelineError> {
    let raw: RawGetBlockResult = serde_json::from_value(value)
        .map_err(|e| PipelineError::RpcFailed(format!("block parse failed: {e}")))?;

    let raw_txs = raw.transactions.unwrap_or_default();
    let mut transactions = Vec::with_capacity(raw_txs.len());

    for raw_tx in raw_txs {
        let success = raw_tx
            .meta
            .as_ref()
            .map(|m| m.err.is_none())
            .unwrap_or(true);

        // Filter failed transactions if configured
        if !index_failed_txs && !success {
            continue;
        }

        let signature = raw_tx
            .transaction
            .signatures
            .first()
            .cloned()
            .unwrap_or_default();

        let instructions = raw_tx
            .transaction
            .message
            .instructions
            .iter()
            .map(parse_raw_instruction)
            .collect::<Result<Vec<_>, _>>()?;

        let inner_instructions = raw_tx
            .meta
            .as_ref()
            .and_then(|m| m.inner_instructions.as_ref())
            .map(|groups| {
                groups
                    .iter()
                    .map(parse_raw_inner_instruction_group)
                    .collect::<Result<Vec<_>, _>>()
            })
            .transpose()?
            .unwrap_or_default();

        // Append v0 loaded addresses (from address lookup tables) to account_keys
        let mut account_keys = raw_tx.transaction.message.account_keys;
        if let Some(meta) = &raw_tx.meta {
            if let Some(loaded) = &meta.loaded_addresses {
                account_keys.extend(loaded.writable.iter().cloned());
                account_keys.extend(loaded.readonly.iter().cloned());
            }
        }

        transactions.push(RpcTransaction {
            signature,
            slot,
            success,
            account_keys,
            instructions,
            inner_instructions,
        });
    }

    Ok(RpcBlock {
        slot,
        block_time: raw.block_time,
        transactions,
    })
}

fn parse_raw_instruction(raw: &RawInstruction) -> Result<RpcInstruction, PipelineError> {
    let data = bs58::decode(&raw.data)
        .into_vec()
        .map_err(|e| PipelineError::RpcFailed(format!("base58 decode failed: {e}")))?;

    Ok(RpcInstruction {
        program_id_index: raw.program_id_index,
        data,
        accounts: raw.accounts.clone(),
    })
}

fn parse_raw_inner_instruction_group(
    raw: &RawInnerInstructionGroup,
) -> Result<RpcInnerInstructionGroup, PipelineError> {
    let instructions = raw
        .instructions
        .iter()
        .map(parse_raw_instruction)
        .collect::<Result<Vec<_>, _>>()?;

    Ok(RpcInnerInstructionGroup {
        index: raw.index,
        instructions,
    })
}

fn decode_base64_account_data(data: &[String]) -> Result<Vec<u8>, PipelineError> {
    use base64::Engine;

    let encoded = data
        .first()
        .ok_or_else(|| PipelineError::RpcFailed("empty account data array".into()))?;

    base64::engine::general_purpose::STANDARD
        .decode(encoded)
        .map_err(|e| PipelineError::RpcFailed(format!("base64 decode failed: {e}")))
}

// ---------------------------------------------------------------------------
// Error classification
// ---------------------------------------------------------------------------

/// Classify JSON-RPC errors into retryable vs permanent.
fn classify_rpc_error(err: JsonRpcError) -> PipelineError {
    match err.code {
        SKIPPED_SLOT_ERROR_CODE => {
            // Slot was skipped — permanent for this slot, handled as Ok(None) by get_block
            PipelineError::SlotSkipped(err.message)
        }
        -32007 | -32010 => {
            // Block cleaned up / not available — permanent for this slot
            PipelineError::SlotSkipped(err.message)
        }
        -32005 => {
            // Node is behind — transient
            PipelineError::RpcFailed(format!("node behind: {}", err.message))
        }
        -32600 | -32601 | -32602 => {
            // Invalid request / method not found / invalid params — permanent
            PipelineError::Fatal(format!("RPC protocol error {}: {}", err.code, err.message))
        }
        _ => {
            // Unknown errors treated as transient (conservative)
            PipelineError::RpcFailed(format!("RPC error {}: {}", err.code, err.message))
        }
    }
}

// ---------------------------------------------------------------------------
// Chunking helpers (pure functions, testable)
// ---------------------------------------------------------------------------

/// Compute (start, end) chunk pairs for `getBlocks` calls respecting the 500K limit.
fn compute_block_chunks(start_slot: u64, end_slot: u64) -> Vec<(u64, u64)> {
    if start_slot > end_slot {
        return Vec::new();
    }

    let mut chunks = Vec::new();
    let mut current = start_slot;

    while current <= end_slot {
        let chunk_end = std::cmp::min(current.saturating_add(MAX_GET_BLOCKS_RANGE - 1), end_slot);
        chunks.push((current, chunk_end));
        if chunk_end >= end_slot {
            break;
        }
        current = chunk_end.saturating_add(1);
    }

    chunks
}

/// Split pubkeys into batches of 100, returning (batch_slice, start_index).
fn batch_pubkeys(pubkeys: &[String]) -> Vec<(&[String], usize)> {
    pubkeys
        .chunks(MAX_MULTIPLE_ACCOUNTS_BATCH)
        .enumerate()
        .map(|(i, chunk)| (chunk, i * MAX_MULTIPLE_ACCOUNTS_BATCH))
        .collect()
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    /// Filter failed transactions from a block (test helper).
    fn filter_failed_transactions(
        transactions: Vec<super::RpcTransaction>,
    ) -> Vec<super::RpcTransaction> {
        transactions.into_iter().filter(|tx| tx.success).collect()
    }
    use super::*;

    // -- Task 7.1: Test is_retryable on all PipelineError variants --

    #[test]
    fn test_is_retryable() {
        assert!(PipelineError::RpcFailed("timeout".into()).is_retryable());
        assert!(PipelineError::WebSocketDisconnect("gone".into()).is_retryable());
        assert!(PipelineError::RateLimited.is_retryable());
        assert!(!PipelineError::Fatal("bad config".into()).is_retryable());

        // Decode and Storage errors are not retryable
        let decode_err = PipelineError::Decode(crate::decoder::DecodeError::UnknownDiscriminator(
            "ff".into(),
        ));
        assert!(!decode_err.is_retryable());
    }

    // -- Task 7.2: Test getBlocks chunking logic --

    #[test]
    fn test_compute_block_chunks_single_small_range() {
        let chunks = compute_block_chunks(0, 100);
        assert_eq!(chunks, vec![(0, 100)]);
    }

    #[test]
    fn test_compute_block_chunks_exact_boundary() {
        let chunks = compute_block_chunks(0, 499_999);
        assert_eq!(chunks, vec![(0, 499_999)]);
    }

    #[test]
    fn test_compute_block_chunks_exceeds_boundary() {
        let chunks = compute_block_chunks(0, 500_000);
        assert_eq!(chunks, vec![(0, 499_999), (500_000, 500_000)]);
    }

    #[test]
    fn test_compute_block_chunks_multiple() {
        let chunks = compute_block_chunks(0, 1_200_000);
        assert_eq!(
            chunks,
            vec![(0, 499_999), (500_000, 999_999), (1_000_000, 1_200_000)]
        );
    }

    #[test]
    fn test_compute_block_chunks_single_slot() {
        let chunks = compute_block_chunks(42, 42);
        assert_eq!(chunks, vec![(42, 42)]);
    }

    #[test]
    fn test_compute_block_chunks_inverted_range() {
        let chunks = compute_block_chunks(100, 50);
        assert!(chunks.is_empty());
    }

    // -- Task 7.3: Test error classification --

    #[test]
    fn test_classify_skipped_slot() {
        let err = classify_rpc_error(JsonRpcError {
            code: -32009,
            message: "Slot 123 was skipped".into(),
        });
        assert!(
            matches!(err, PipelineError::SlotSkipped(_)),
            "expected SlotSkipped, got: {err}"
        );
    }

    #[test]
    fn test_classify_block_unavailable() {
        for code in [-32007, -32010] {
            let err = classify_rpc_error(JsonRpcError {
                code,
                message: "block not available".into(),
            });
            assert!(
                matches!(err, PipelineError::SlotSkipped(_)),
                "expected SlotSkipped for code {code}, got: {err}"
            );
        }
    }

    #[test]
    fn test_classify_node_behind() {
        let err = classify_rpc_error(JsonRpcError {
            code: -32005,
            message: "Node is behind".into(),
        });
        match err {
            PipelineError::RpcFailed(msg) => assert!(msg.starts_with("node behind")),
            other => panic!("expected RpcFailed, got: {other}"),
        }
    }

    #[test]
    fn test_classify_protocol_errors_are_fatal() {
        for code in [-32600, -32601, -32602] {
            let err = classify_rpc_error(JsonRpcError {
                code,
                message: "bad".into(),
            });
            assert!(
                matches!(err, PipelineError::Fatal(_)),
                "expected Fatal for code {code}, got: {err}"
            );
        }
    }

    #[test]
    fn test_classify_unknown_error_is_retryable() {
        let err = classify_rpc_error(JsonRpcError {
            code: -32000,
            message: "unknown".into(),
        });
        assert!(err.is_retryable());
    }

    // -- Task 7.4: Test failed transaction filtering --

    #[test]
    fn test_filter_failed_transactions_removes_failures() {
        let txs = vec![
            RpcTransaction {
                signature: "sig1".into(),
                slot: 100,
                success: true,
                account_keys: vec![],
                instructions: vec![],
                inner_instructions: vec![],
            },
            RpcTransaction {
                signature: "sig2".into(),
                slot: 100,
                success: false,
                account_keys: vec![],
                instructions: vec![],
                inner_instructions: vec![],
            },
            RpcTransaction {
                signature: "sig3".into(),
                slot: 100,
                success: true,
                account_keys: vec![],
                instructions: vec![],
                inner_instructions: vec![],
            },
        ];

        let filtered = filter_failed_transactions(txs);
        assert_eq!(filtered.len(), 2);
        assert_eq!(filtered[0].signature, "sig1");
        assert_eq!(filtered[1].signature, "sig3");
    }

    #[test]
    fn test_filter_failed_transactions_keeps_all_when_all_success() {
        let txs = vec![RpcTransaction {
            signature: "sig1".into(),
            slot: 100,
            success: true,
            account_keys: vec![],
            instructions: vec![],
            inner_instructions: vec![],
        }];

        let filtered = filter_failed_transactions(txs);
        assert_eq!(filtered.len(), 1);
    }

    // -- Task 7.5: Test RPC response deserialization --

    #[test]
    fn test_parse_block_response() {
        let json = serde_json::json!({
            "blockTime": 1_700_000_000i64,
            "transactions": [
                {
                    "transaction": {
                        "message": {
                            "accountKeys": ["key1", "key2", "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"],
                            "instructions": [
                                {
                                    "programIdIndex": 2,
                                    "data": "3Bxs4h24hBtQy9rw",
                                    "accounts": [0, 1]
                                }
                            ]
                        },
                        "signatures": ["5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"]
                    },
                    "meta": {
                        "err": null,
                        "innerInstructions": [
                            {
                                "index": 0,
                                "instructions": [
                                    {
                                        "programIdIndex": 1,
                                        "data": "11",
                                        "accounts": [0]
                                    }
                                ]
                            }
                        ]
                    }
                },
                {
                    "transaction": {
                        "message": {
                            "accountKeys": ["keyA"],
                            "instructions": []
                        },
                        "signatures": ["failedSig"]
                    },
                    "meta": {
                        "err": {"InstructionError": [0, "Custom"]},
                        "innerInstructions": []
                    }
                }
            ]
        });

        // With index_failed_txs = false, should filter out the failed tx
        let block = parse_block(42, json.clone(), false).expect("parse_block failed");

        assert_eq!(block.slot, 42);
        assert_eq!(block.block_time, Some(1_700_000_000));
        assert_eq!(block.transactions.len(), 1);
        assert_eq!(
            block.transactions[0].signature,
            "5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp"
        );
        assert!(block.transactions[0].success);
        assert_eq!(block.transactions[0].instructions.len(), 1);
        assert_eq!(block.transactions[0].instructions[0].program_id_index, 2);
        assert_eq!(block.transactions[0].inner_instructions.len(), 1);
        assert_eq!(
            block.transactions[0].inner_instructions[0]
                .instructions
                .len(),
            1
        );

        // With index_failed_txs = true, should keep both
        let block_all = parse_block(42, json, true).expect("parse_block failed");

        assert_eq!(block_all.transactions.len(), 2);
        assert!(!block_all.transactions[1].success);
    }

    #[test]
    fn test_parse_get_blocks_response() {
        let json = serde_json::json!([100, 200, 300, 400]);
        let slots: Vec<u64> = serde_json::from_value(json).expect("parse failed");

        assert_eq!(slots, vec![100, 200, 300, 400]);
    }

    // -- Test: v0 loadedAddresses merged into account keys (AC7) --

    #[test]
    fn test_parse_block_with_loaded_addresses() {
        let json = serde_json::json!({
            "blockTime": 1_700_000_000i64,
            "transactions": [
                {
                    "transaction": {
                        "message": {
                            "accountKeys": ["staticKey1", "staticKey2"],
                            "instructions": [
                                {
                                    "programIdIndex": 1,
                                    "data": "11",
                                    "accounts": [0]
                                }
                            ]
                        },
                        "signatures": ["v0TxSig"]
                    },
                    "meta": {
                        "err": null,
                        "innerInstructions": [],
                        "loadedAddresses": {
                            "writable": ["loadedWritable1", "loadedWritable2"],
                            "readonly": ["loadedReadonly1"]
                        }
                    }
                }
            ]
        });

        let block = parse_block(100, json, false).expect("parse_block with loadedAddresses");

        assert_eq!(block.transactions.len(), 1);
        let tx = &block.transactions[0];
        assert_eq!(
            tx.account_keys,
            vec![
                "staticKey1",
                "staticKey2",
                "loadedWritable1",
                "loadedWritable2",
                "loadedReadonly1",
            ]
        );
    }

    // -- Task 7.6: Test batch pubkeys --

    #[test]
    fn test_batch_pubkeys_small() {
        let keys: Vec<String> = (0..5).map(|i| format!("key{i}")).collect();
        let batches = batch_pubkeys(&keys);
        assert_eq!(batches.len(), 1);
        assert_eq!(batches[0].0.len(), 5);
        assert_eq!(batches[0].1, 0);
    }

    #[test]
    fn test_batch_pubkeys_exact_100() {
        let keys: Vec<String> = (0..100).map(|i| format!("key{i}")).collect();
        let batches = batch_pubkeys(&keys);
        assert_eq!(batches.len(), 1);
        assert_eq!(batches[0].0.len(), 100);
    }

    #[test]
    fn test_batch_pubkeys_over_100() {
        let keys: Vec<String> = (0..250).map(|i| format!("key{i}")).collect();
        let batches = batch_pubkeys(&keys);
        assert_eq!(batches.len(), 3);
        assert_eq!(batches[0].0.len(), 100);
        assert_eq!(batches[0].1, 0);
        assert_eq!(batches[1].0.len(), 100);
        assert_eq!(batches[1].1, 100);
        assert_eq!(batches[2].0.len(), 50);
        assert_eq!(batches[2].1, 200);
    }

    #[test]
    fn test_batch_pubkeys_empty() {
        let keys: Vec<String> = vec![];
        let batches = batch_pubkeys(&keys);
        assert!(batches.is_empty());
    }

    // -- Test base64 account data decoding --

    #[test]
    fn test_decode_base64_account_data() {
        use base64::Engine;
        let original = vec![1u8, 2, 3, 4, 5];
        let encoded = base64::engine::general_purpose::STANDARD.encode(&original);
        let data = vec![encoded, "base64".to_string()];
        let decoded = decode_base64_account_data(&data).expect("decode failed");
        assert_eq!(decoded, original);
    }

    #[test]
    fn test_decode_base64_account_data_empty_array() {
        let data: Vec<String> = vec![];
        let result = decode_base64_account_data(&data);
        assert!(result.is_err());
    }
}
